apiVersion: v1
kind: Service
metadata:
  name: object-tracker
  namespace: uav-edge
  labels:
    app: object-tracker
spec:
  selector:
    app: object-tracker
  ports:
    - port: 8007
      targetPort: 8000
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: object-tracker
  namespace: uav-edge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: object-tracker
  template:
    metadata:
      labels:
        app: object-tracker
    spec:
      nodeSelector:
        kubernetes.io/hostname: uav-node3
      containers:
        - name: object-tracker
          image: uav-edge-object-tracker:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          env:
            - name: SERVICE_ROLE
              value: "object-tracker"
            - name: SERVICE_PORT
              value: "8000"
            - name: DOWNSTREAM_URLS
              value: "http://decision-maker:8009"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://jaeger:4317"
          resources:
            requests:
              cpu: "300m"
              memory: "256Mi"
            limits:
              cpu: "800m"
              memory: "512Mi"
